<?class_parents
class Zephir\CompilationContext 
{public ?Zephir\AliasManager $aliasManager = class Zephir\AliasManager 
{protected array $aliases = [...] }; public ?Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{protected Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; protected Zephir\Config $config = class Zephir\Config 
{... }; protected string $kernelsPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/kernel'; protected string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates' }; public ?Zephir\BranchManager $branchManager = class Zephir\BranchManager 
{protected ?Zephir\Branch $currentBranch = class Zephir\Branch 
{... }; protected int $level = 2; protected ?Zephir\Branch $rootBranch = class Zephir\Branch 
{... }; protected int $uniqueId = 3 }; public ?Zephir\Cache\Manager $cacheManager = class Zephir\Cache\Manager 
{protected ?Zephir\Cache\ClassEntryCache $classEntryCache = NULL; protected ?Zephir\Cache\FunctionCache $functionCache = NULL; protected ?Zephir\Passes\CallGathererPass $gatherer = NULL; protected ?Zephir\Cache\MethodCache $methodCache = NULL; protected ?Zephir\Cache\StaticMethodCache $staticMethodCache = NULL }; public ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{protected string $name = '0__closure'; protected bool $abstract = FALSE; protected ?Zephir\AliasManager $aliasManager = NULL; protected Zephir\Compiler $compiler = class Zephir\Compiler 
{... }; protected array $constants = [...]; protected int $dependencyRank = 0; protected string $docBlock = ''; protected ?string $extendsClass = NULL; protected ?Zephir\Class\Definition\AbstractDefinition $extendsClassDefinition = NULL; protected bool $external = FALSE; protected bool $final = TRUE; protected array $implementedInterfaceDefinitions = [...]; protected array $interfaces = [...]; protected bool $isBundled = FALSE; protected array $methods = [...]; protected array $originalNode = [...]; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $properties = [...]; protected string $shortName = '0__closure'; protected string $type = 'class'; protected string $namespace = 'koalas' }; public ?Zephir\Code\Printer $codePrinter = class Zephir\Code\Printer 
{protected string $code = ''; protected int $currentPrints = 0; protected string $lastLine = ''; protected int $level = 1 }; public ?Zephir\Compiler $compiler = class Zephir\Compiler 
{public array $functionDefinitions = [...]; private array $anonymousFiles = [...]; private array $compiledFiles = [...]; private array $constants = [...]; private array $definitions = [...]; private array $externalDependencies = [...]; private array $extraFiles = [...]; private Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; private array $files = [...]; private array $globals = [...]; private array $internalInitializers = [...]; private ?string $optimizersPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Optimizers'; private ?string $prototypesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/prototypes'; private Zephir\Backend\StringsManager $stringManager = class Zephir\Backend\StringsManager 
{... }; private ?string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates'; private Zephir\Config $config = class Zephir\Config 
{... }; public Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{... }; private Zephir\Parser\Manager $parserManager = class Zephir\Parser\Manager 
{... }; private Zephir\FileSystem\FileSystemInterface $filesystem = class Zephir\FileSystem\HardDisk 
{... }; private Zephir\Compiler\CompilerFileFactory $compilerFileFactory = class Zephir\Compiler\CompilerFileFactory 
{... }; protected $logger = class Monolog\Logger 
{... } }; public ?Zephir\Config $config = class Zephir\Config 
{protected bool $changed = FALSE; private array $container = [...] }; public int $currentBranch = 1; public ?Zephir\Class\Method\Method $currentMethod = class Zephir\Class\Method\Method 
{public bool $optimizable = TRUE; protected ?Zephir\Passes\CallGathererPass $callGathererPass = NULL; protected bool $isAbstract = FALSE; protected bool $isBundled = FALSE; protected bool $isFinal = TRUE; protected bool $isInitializer = FALSE; protected bool $isInternal = FALSE; protected bool $isPublic = TRUE; protected bool $isStatic = FALSE; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected array $mayBeArgTypes = [...]; protected bool $mixed = FALSE; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $returnClassTypes = [...]; protected array $returnTypes = [...]; protected ?array $returnTypesRaw = NULL; protected array $staticVariables = [...]; protected ?Zephir\Passes\StaticTypeInference $typeInference = NULL; protected bool $void = FALSE; protected ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{... }; protected array $visibility = [...]; protected string $name = '__invoke'; protected ?Zephir\Class\Method\Parameters $parameters = class Zephir\Class\Method\Parameters 
{... }; protected ?Zephir\StatementsBlock $statements = class Zephir\StatementsBlock 
{... }; protected ?string $docblock = NULL; protected ?array $expression = [...] }; public int $currentTryCatch = 0; public array $cycleBlocks = []; public ?Zephir\Cache\FunctionCache $functionCache = NULL; public ?Zephir\Code\Printer $headerPrinter = NULL; public ?Zephir\HeadersManager $headersManager = class Zephir\HeadersManager 
{protected array $headers = [...]; protected array $headersFirst = [...]; protected array $headersLast = [...] }; public int $insideCycle = 0; public int $insideSwitch = 0; public int $insideTryCatch = 0; public ?Psr\Log\LoggerInterface $logger = class Monolog\Logger 
{protected $name = 'zephir'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone 
{... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $fiberLogDepth = class WeakMap 
{... }; private $detectCycles = TRUE }; public bool $staticContext = FALSE; public ?Zephir\StringsManager $stringsManager = class Zephir\Backend\StringsManager 
{protected array $concatKeys = [...] }; public ?Zephir\SymbolTable $symbolTable = class Zephir\SymbolTable 
{protected array $branchTempVariables = [...]; protected array $branchVariables = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected bool $mustGrownStack = FALSE; protected int $tempVarCount = 0; protected Zephir\CompilationContext $compilationContext = ... }; public ?Zephir\Passes\StaticTypeInference $typeInference = NULL }) phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/CompilerFileAnonymous.php:92
    0.0471   10681744   7. Zephir\Class\Definition\Definition->compile($compilationContext = class Zephir\CompilationContext 
{public ?Zephir\AliasManager $aliasManager = class Zephir\AliasManager 
{protected array $aliases = [...] }; public ?Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{protected Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; protected Zephir\Config $config = class Zephir\Config 
{... }; protected string $kernelsPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/kernel'; protected string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates' }; public ?Zephir\BranchManager $branchManager = class Zephir\BranchManager 
{protected ?Zephir\Branch $currentBranch = class Zephir\Branch 
{... }; protected int $level = 2; protected ?Zephir\Branch $rootBranch = class Zephir\Branch 
{... }; protected int $uniqueId = 3 }; public ?Zephir\Cache\Manager $cacheManager = class Zephir\Cache\Manager 
{protected ?Zephir\Cache\ClassEntryCache $classEntryCache = NULL; protected ?Zephir\Cache\FunctionCache $functionCache = NULL; protected ?Zephir\Passes\CallGathererPass $gatherer = NULL; protected ?Zephir\Cache\MethodCache $methodCache = NULL; protected ?Zephir\Cache\StaticMethodCache $staticMethodCache = NULL }; public ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{protected string $name = '0__closure'; protected bool $abstract = FALSE; protected ?Zephir\AliasManager $aliasManager = NULL; protected Zephir\Compiler $compiler = class Zephir\Compiler 
{... }; protected array $constants = [...]; protected int $dependencyRank = 0; protected string $docBlock = ''; protected ?string $extendsClass = NULL; protected ?Zephir\Class\Definition\AbstractDefinition $extendsClassDefinition = NULL; protected bool $external = FALSE; protected bool $final = TRUE; protected array $implementedInterfaceDefinitions = [...]; protected array $interfaces = [...]; protected bool $isBundled = FALSE; protected array $methods = [...]; protected array $originalNode = [...]; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $properties = [...]; protected string $shortName = '0__closure'; protected string $type = 'class'; protected string $namespace = 'koalas' }; public ?Zephir\Code\Printer $codePrinter = class Zephir\Code\Printer 
{protected string $code = ''; protected int $currentPrints = 0; protected string $lastLine = ''; protected int $level = 1 }; public ?Zephir\Compiler $compiler = class Zephir\Compiler 
{public array $functionDefinitions = [...]; private array $anonymousFiles = [...]; private array $compiledFiles = [...]; private array $constants = [...]; private array $definitions = [...]; private array $externalDependencies = [...]; private array $extraFiles = [...]; private Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; private array $files = [...]; private array $globals = [...]; private array $internalInitializers = [...]; private ?string $optimizersPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Optimizers'; private ?string $prototypesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/prototypes'; private Zephir\Backend\StringsManager $stringManager = class Zephir\Backend\StringsManager 
{... }; private ?string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates'; private Zephir\Config $config = class Zephir\Config 
{... }; public Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{... }; private Zephir\Parser\Manager $parserManager = class Zephir\Parser\Manager 
{... }; private Zephir\FileSystem\FileSystemInterface $filesystem = class Zephir\FileSystem\HardDisk 
{... }; private Zephir\Compiler\CompilerFileFactory $compilerFileFactory = class Zephir\Compiler\CompilerFileFactory 
{... }; protected $logger = class Monolog\Logger 
{... } }; public ?Zephir\Config $config = class Zephir\Config 
{protected bool $changed = FALSE; private array $container = [...] }; public int $currentBranch = 1; public ?Zephir\Class\Method\Method $currentMethod = class Zephir\Class\Method\Method 
{public bool $optimizable = TRUE; protected ?Zephir\Passes\CallGathererPass $callGathererPass = NULL; protected bool $isAbstract = FALSE; protected bool $isBundled = FALSE; protected bool $isFinal = TRUE; protected bool $isInitializer = FALSE; protected bool $isInternal = FALSE; protected bool $isPublic = TRUE; protected bool $isStatic = FALSE; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected array $mayBeArgTypes = [...]; protected bool $mixed = FALSE; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $returnClassTypes = [...]; protected array $returnTypes = [...]; protected ?array $returnTypesRaw = NULL; protected array $staticVariables = [...]; protected ?Zephir\Passes\StaticTypeInference $typeInference = NULL; protected bool $void = FALSE; protected ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{... }; protected array $visibility = [...]; protected string $name = '__invoke'; protected ?Zephir\Class\Method\Parameters $parameters = class Zephir\Class\Method\Parameters 
{... }; protected ?Zephir\StatementsBlock $statements = class Zephir\StatementsBlock 
{... }; protected ?string $docblock = NULL; protected ?array $expression = [...] }; public int $currentTryCatch = 0; public array $cycleBlocks = []; public ?Zephir\Cache\FunctionCache $functionCache = NULL; public ?Zephir\Code\Printer $headerPrinter = NULL; public ?Zephir\HeadersManager $headersManager = class Zephir\HeadersManager 
{protected array $headers = [...]; protected array $headersFirst = [...]; protected array $headersLast = [...] }; public int $insideCycle = 0; public int $insideSwitch = 0; public int $insideTryCatch = 0; public ?Psr\Log\LoggerInterface $logger = class Monolog\Logger 
{protected $name = 'zephir'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone 
{... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $fiberLogDepth = class WeakMap 
{... }; private $detectCycles = TRUE }; public bool $staticContext = FALSE; public ?Zephir\StringsManager $stringsManager = class Zephir\Backend\StringsManager 
{protected array $concatKeys = [...] }; public ?Zephir\SymbolTable $symbolTable = class Zephir\SymbolTable 
{protected array $branchTempVariables = [...]; protected array $branchVariables = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected bool $mustGrownStack = FALSE; protected int $tempVarCount = 0; protected Zephir\CompilationContext $compilationContext = ... }; public ?Zephir\Passes\StaticTypeInference $typeInference = NULL }) phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/CompilerFileAnonymous.php:177
    0.0471   10682328   8. Zephir\Class\Method\Method->compile($compilationContext = class Zephir\CompilationContext 
{public ?Zephir\AliasManager $aliasManager = class Zephir\AliasManager 
{protected array $aliases = [...] }; public ?Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{protected Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; protected Zephir\Config $config = class Zephir\Config 
{... }; protected string $kernelsPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/kernel'; protected string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates' }; public ?Zephir\BranchManager $branchManager = class Zephir\BranchManager 
{protected ?Zephir\Branch $currentBranch = class Zephir\Branch 
{... }; protected int $level = 2; protected ?Zephir\Branch $rootBranch = class Zephir\Branch 
{... }; protected int $uniqueId = 3 }; public ?Zephir\Cache\Manager $cacheManager = class Zephir\Cache\Manager 
{protected ?Zephir\Cache\ClassEntryCache $classEntryCache = NULL; protected ?Zephir\Cache\FunctionCache $functionCache = NULL; protected ?Zephir\Passes\CallGathererPass $gatherer = NULL; protected ?Zephir\Cache\MethodCache $methodCache = NULL; protected ?Zephir\Cache\StaticMethodCache $staticMethodCache = NULL }; public ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{protected string $name = '0__closure'; protected bool $abstract = FALSE; protected ?Zephir\AliasManager $aliasManager = NULL; protected Zephir\Compiler $compiler = class Zephir\Compiler 
{... }; protected array $constants = [...]; protected int $dependencyRank = 0; protected string $docBlock = ''; protected ?string $extendsClass = NULL; protected ?Zephir\Class\Definition\AbstractDefinition $extendsClassDefinition = NULL; protected bool $external = FALSE; protected bool $final = TRUE; protected array $implementedInterfaceDefinitions = [...]; protected array $interfaces = [...]; protected bool $isBundled = FALSE; protected array $methods = [...]; protected array $originalNode = [...]; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $properties = [...]; protected string $shortName = '0__closure'; protected string $type = 'class'; protected string $namespace = 'koalas' }; public ?Zephir\Code\Printer $codePrinter = class Zephir\Code\Printer 
{protected string $code = ''; protected int $currentPrints = 0; protected string $lastLine = ''; protected int $level = 1 }; public ?Zephir\Compiler $compiler = class Zephir\Compiler 
{public array $functionDefinitions = [...]; private array $anonymousFiles = [...]; private array $compiledFiles = [...]; private array $constants = [...]; private array $definitions = [...]; private array $externalDependencies = [...]; private array $extraFiles = [...]; private Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; private array $files = [...]; private array $globals = [...]; private array $internalInitializers = [...]; private ?string $optimizersPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Optimizers'; private ?string $prototypesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/prototypes'; private Zephir\Backend\StringsManager $stringManager = class Zephir\Backend\StringsManager 
{... }; private ?string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates'; private Zephir\Config $config = class Zephir\Config 
{... }; public Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{... }; private Zephir\Parser\Manager $parserManager = class Zephir\Parser\Manager 
{... }; private Zephir\FileSystem\FileSystemInterface $filesystem = class Zephir\FileSystem\HardDisk 
{... }; private Zephir\Compiler\CompilerFileFactory $compilerFileFactory = class Zephir\Compiler\CompilerFileFactory 
{... }; protected $logger = class Monolog\Logger 
{... } }; public ?Zephir\Config $config = class Zephir\Config 
{protected bool $changed = FALSE; private array $container = [...] }; public int $currentBranch = 1; public ?Zephir\Class\Method\Method $currentMethod = class Zephir\Class\Method\Method 
{public bool $optimizable = TRUE; protected ?Zephir\Passes\CallGathererPass $callGathererPass = NULL; protected bool $isAbstract = FALSE; protected bool $isBundled = FALSE; protected bool $isFinal = TRUE; protected bool $isInitializer = FALSE; protected bool $isInternal = FALSE; protected bool $isPublic = TRUE; protected bool $isStatic = FALSE; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected array $mayBeArgTypes = [...]; protected bool $mixed = FALSE; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $returnClassTypes = [...]; protected array $returnTypes = [...]; protected ?array $returnTypesRaw = NULL; protected array $staticVariables = [...]; protected ?Zephir\Passes\StaticTypeInference $typeInference = NULL; protected bool $void = FALSE; protected ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{... }; protected array $visibility = [...]; protected string $name = '__invoke'; protected ?Zephir\Class\Method\Parameters $parameters = class Zephir\Class\Method\Parameters 
{... }; protected ?Zephir\StatementsBlock $statements = class Zephir\StatementsBlock 
{... }; protected ?string $docblock = NULL; protected ?array $expression = [...] }; public int $currentTryCatch = 0; public array $cycleBlocks = []; public ?Zephir\Cache\FunctionCache $functionCache = NULL; public ?Zephir\Code\Printer $headerPrinter = NULL; public ?Zephir\HeadersManager $headersManager = class Zephir\HeadersManager 
{protected array $headers = [...]; protected array $headersFirst = [...]; protected array $headersLast = [...] }; public int $insideCycle = 0; public int $insideSwitch = 0; public int $insideTryCatch = 0; public ?Psr\Log\LoggerInterface $logger = class Monolog\Logger 
{protected $name = 'zephir'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone 
{... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $fiberLogDepth = class WeakMap 
{... }; private $detectCycles = TRUE }; public bool $staticContext = FALSE; public ?Zephir\StringsManager $stringsManager = class Zephir\Backend\StringsManager 
{protected array $concatKeys = [...] }; public ?Zephir\SymbolTable $symbolTable = class Zephir\SymbolTable 
{protected array $branchTempVariables = [...]; protected array $branchVariables = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected bool $mustGrownStack = FALSE; protected int $tempVarCount = 0; protected Zephir\CompilationContext $compilationContext = ... }; public ?Zephir\Passes\StaticTypeInference $typeInference = NULL }) phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Class/Definition/Definition.php:609
    0.0472   10693520   9. Zephir\StatementsBlock->compile($compilationContext = class Zephir\CompilationContext 
{public ?Zephir\AliasManager $aliasManager = class Zephir\AliasManager 
{protected array $aliases = [...] }; public ?Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{protected Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; protected Zephir\Config $config = class Zephir\Config 
{... }; protected string $kernelsPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/kernel'; protected string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates' }; public ?Zephir\BranchManager $branchManager = class Zephir\BranchManager 
{protected ?Zephir\Branch $currentBranch = class Zephir\Branch 
{... }; protected int $level = 2; protected ?Zephir\Branch $rootBranch = class Zephir\Branch 
{... }; protected int $uniqueId = 3 }; public ?Zephir\Cache\Manager $cacheManager = class Zephir\Cache\Manager 
{protected ?Zephir\Cache\ClassEntryCache $classEntryCache = NULL; protected ?Zephir\Cache\FunctionCache $functionCache = NULL; protected ?Zephir\Passes\CallGathererPass $gatherer = NULL; protected ?Zephir\Cache\MethodCache $methodCache = NULL; protected ?Zephir\Cache\StaticMethodCache $staticMethodCache = NULL }; public ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{protected string $name = '0__closure'; protected bool $abstract = FALSE; protected ?Zephir\AliasManager $aliasManager = NULL; protected Zephir\Compiler $compiler = class Zephir\Compiler 
{... }; protected array $constants = [...]; protected int $dependencyRank = 0; protected string $docBlock = ''; protected ?string $extendsClass = NULL; protected ?Zephir\Class\Definition\AbstractDefinition $extendsClassDefinition = NULL; protected bool $external = FALSE; protected bool $final = TRUE; protected array $implementedInterfaceDefinitions = [...]; protected array $interfaces = [...]; protected bool $isBundled = FALSE; protected array $methods = [...]; protected array $originalNode = [...]; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $properties = [...]; protected string $shortName = '0__closure'; protected string $type = 'class'; protected string $namespace = 'koalas' }; public ?Zephir\Code\Printer $codePrinter = class Zephir\Code\Printer 
{protected string $code = ''; protected int $currentPrints = 0; protected string $lastLine = ''; protected int $level = 1 }; public ?Zephir\Compiler $compiler = class Zephir\Compiler 
{public array $functionDefinitions = [...]; private array $anonymousFiles = [...]; private array $compiledFiles = [...]; private array $constants = [...]; private array $definitions = [...]; private array $externalDependencies = [...]; private array $extraFiles = [...]; private Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; private array $files = [...]; private array $globals = [...]; private array $internalInitializers = [...]; private ?string $optimizersPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Optimizers'; private ?string $prototypesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/prototypes'; private Zephir\Backend\StringsManager $stringManager = class Zephir\Backend\StringsManager 
{... }; private ?string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates'; private Zephir\Config $config = class Zephir\Config 
{... }; public Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{... }; private Zephir\Parser\Manager $parserManager = class Zephir\Parser\Manager 
{... }; private Zephir\FileSystem\FileSystemInterface $filesystem = class Zephir\FileSystem\HardDisk 
{... }; private Zephir\Compiler\CompilerFileFactory $compilerFileFactory = class Zephir\Compiler\CompilerFileFactory 
{... }; protected $logger = class Monolog\Logger 
{... } }; public ?Zephir\Config $config = class Zephir\Config 
{protected bool $changed = FALSE; private array $container = [...] }; public int $currentBranch = 1; public ?Zephir\Class\Method\Method $currentMethod = class Zephir\Class\Method\Method 
{public bool $optimizable = TRUE; protected ?Zephir\Passes\CallGathererPass $callGathererPass = NULL; protected bool $isAbstract = FALSE; protected bool $isBundled = FALSE; protected bool $isFinal = TRUE; protected bool $isInitializer = FALSE; protected bool $isInternal = FALSE; protected bool $isPublic = TRUE; protected bool $isStatic = FALSE; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected array $mayBeArgTypes = [...]; protected bool $mixed = FALSE; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $returnClassTypes = [...]; protected array $returnTypes = [...]; protected ?array $returnTypesRaw = NULL; protected array $staticVariables = [...]; protected ?Zephir\Passes\StaticTypeInference $typeInference = NULL; protected bool $void = FALSE; protected ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{... }; protected array $visibility = [...]; protected string $name = '__invoke'; protected ?Zephir\Class\Method\Parameters $parameters = class Zephir\Class\Method\Parameters 
{... }; protected ?Zephir\StatementsBlock $statements = class Zephir\StatementsBlock 
{... }; protected ?string $docblock = NULL; protected ?array $expression = [...] }; public int $currentTryCatch = 0; public array $cycleBlocks = []; public ?Zephir\Cache\FunctionCache $functionCache = NULL; public ?Zephir\Code\Printer $headerPrinter = NULL; public ?Zephir\HeadersManager $headersManager = class Zephir\HeadersManager 
{protected array $headers = [...]; protected array $headersFirst = [...]; protected array $headersLast = [...] }; public int $insideCycle = 0; public int $insideSwitch = 0; public int $insideTryCatch = 0; public ?Psr\Log\LoggerInterface $logger = class Monolog\Logger 
{protected $name = 'zephir'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone 
{... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $fiberLogDepth = class WeakMap 
{... }; private $detectCycles = TRUE }; public bool $staticContext = FALSE; public ?Zephir\StringsManager $stringsManager = class Zephir\Backend\StringsManager 
{protected array $concatKeys = [...] }; public ?Zephir\SymbolTable $symbolTable = class Zephir\SymbolTable 
{protected array $branchTempVariables = [...]; protected array $branchVariables = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected bool $mustGrownStack = FALSE; protected int $tempVarCount = 0; protected Zephir\CompilationContext $compilationContext = ... }; public ?Zephir\Passes\StaticTypeInference $typeInference = NULL }, $unreachable = FALSE, $branchType = 0) phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Class/Method/Method.php:1011
    0.0472   10693816  10. Zephir\Statements\ReturnStatement->compile($compilationContext = class Zephir\CompilationContext 
{public ?Zephir\AliasManager $aliasManager = class Zephir\AliasManager 
{protected array $aliases = [...] }; public ?Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{protected Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; protected Zephir\Config $config = class Zephir\Config 
{... }; protected string $kernelsPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/kernel'; protected string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates' }; public ?Zephir\BranchManager $branchManager = class Zephir\BranchManager 
{protected ?Zephir\Branch $currentBranch = class Zephir\Branch 
{... }; protected int $level = 2; protected ?Zephir\Branch $rootBranch = class Zephir\Branch 
{... }; protected int $uniqueId = 3 }; public ?Zephir\Cache\Manager $cacheManager = class Zephir\Cache\Manager 
{protected ?Zephir\Cache\ClassEntryCache $classEntryCache = NULL; protected ?Zephir\Cache\FunctionCache $functionCache = NULL; protected ?Zephir\Passes\CallGathererPass $gatherer = NULL; protected ?Zephir\Cache\MethodCache $methodCache = NULL; protected ?Zephir\Cache\StaticMethodCache $staticMethodCache = NULL }; public ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{protected string $name = '0__closure'; protected bool $abstract = FALSE; protected ?Zephir\AliasManager $aliasManager = NULL; protected Zephir\Compiler $compiler = class Zephir\Compiler 
{... }; protected array $constants = [...]; protected int $dependencyRank = 0; protected string $docBlock = ''; protected ?string $extendsClass = NULL; protected ?Zephir\Class\Definition\AbstractDefinition $extendsClassDefinition = NULL; protected bool $external = FALSE; protected bool $final = TRUE; protected array $implementedInterfaceDefinitions = [...]; protected array $interfaces = [...]; protected bool $isBundled = FALSE; protected array $methods = [...]; protected array $originalNode = [...]; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $properties = [...]; protected string $shortName = '0__closure'; protected string $type = 'class'; protected string $namespace = 'koalas' }; public ?Zephir\Code\Printer $codePrinter = class Zephir\Code\Printer 
{protected string $code = ''; protected int $currentPrints = 0; protected string $lastLine = ''; protected int $level = 1 }; public ?Zephir\Compiler $compiler = class Zephir\Compiler 
{public array $functionDefinitions = [...]; private array $anonymousFiles = [...]; private array $compiledFiles = [...]; private array $constants = [...]; private array $definitions = [...]; private array $externalDependencies = [...]; private array $extraFiles = [...]; private Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; private array $files = [...]; private array $globals = [...]; private array $internalInitializers = [...]; private ?string $optimizersPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Optimizers'; private ?string $prototypesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/prototypes'; private Zephir\Backend\StringsManager $stringManager = class Zephir\Backend\StringsManager 
{... }; private ?string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates'; private Zephir\Config $config = class Zephir\Config 
{... }; public Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{... }; private Zephir\Parser\Manager $parserManager = class Zephir\Parser\Manager 
{... }; private Zephir\FileSystem\FileSystemInterface $filesystem = class Zephir\FileSystem\HardDisk 
{... }; private Zephir\Compiler\CompilerFileFactory $compilerFileFactory = class Zephir\Compiler\CompilerFileFactory 
{... }; protected $logger = class Monolog\Logger 
{... } }; public ?Zephir\Config $config = class Zephir\Config 
{protected bool $changed = FALSE; private array $container = [...] }; public int $currentBranch = 1; public ?Zephir\Class\Method\Method $currentMethod = class Zephir\Class\Method\Method 
{public bool $optimizable = TRUE; protected ?Zephir\Passes\CallGathererPass $callGathererPass = NULL; protected bool $isAbstract = FALSE; protected bool $isBundled = FALSE; protected bool $isFinal = TRUE; protected bool $isInitializer = FALSE; protected bool $isInternal = FALSE; protected bool $isPublic = TRUE; protected bool $isStatic = FALSE; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected array $mayBeArgTypes = [...]; protected bool $mixed = FALSE; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $returnClassTypes = [...]; protected array $returnTypes = [...]; protected ?array $returnTypesRaw = NULL; protected array $staticVariables = [...]; protected ?Zephir\Passes\StaticTypeInference $typeInference = NULL; protected bool $void = FALSE; protected ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{... }; protected array $visibility = [...]; protected string $name = '__invoke'; protected ?Zephir\Class\Method\Parameters $parameters = class Zephir\Class\Method\Parameters 
{... }; protected ?Zephir\StatementsBlock $statements = class Zephir\StatementsBlock 
{... }; protected ?string $docblock = NULL; protected ?array $expression = [...] }; public int $currentTryCatch = 0; public array $cycleBlocks = []; public ?Zephir\Cache\FunctionCache $functionCache = NULL; public ?Zephir\Code\Printer $headerPrinter = NULL; public ?Zephir\HeadersManager $headersManager = class Zephir\HeadersManager 
{protected array $headers = [...]; protected array $headersFirst = [...]; protected array $headersLast = [...] }; public int $insideCycle = 0; public int $insideSwitch = 0; public int $insideTryCatch = 0; public ?Psr\Log\LoggerInterface $logger = class Monolog\Logger 
{protected $name = 'zephir'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone 
{... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $fiberLogDepth = class WeakMap 
{... }; private $detectCycles = TRUE }; public bool $staticContext = FALSE; public ?Zephir\StringsManager $stringsManager = class Zephir\Backend\StringsManager 
{protected array $concatKeys = [...] }; public ?Zephir\SymbolTable $symbolTable = class Zephir\SymbolTable 
{protected array $branchTempVariables = [...]; protected array $branchVariables = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected bool $mustGrownStack = FALSE; protected int $tempVarCount = 0; protected Zephir\CompilationContext $compilationContext = ... }; public ?Zephir\Passes\StaticTypeInference $typeInference = NULL }) phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/StatementsBlock.php:231
    0.0472   10693976  11. Zephir\Expression->compile($compilationContext = class Zephir\CompilationContext 
{public ?Zephir\AliasManager $aliasManager = class Zephir\AliasManager 
{protected array $aliases = [...] }; public ?Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{protected Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; protected Zephir\Config $config = class Zephir\Config 
{... }; protected string $kernelsPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/kernel'; protected string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates' }; public ?Zephir\BranchManager $branchManager = class Zephir\BranchManager 
{protected ?Zephir\Branch $currentBranch = class Zephir\Branch 
{... }; protected int $level = 2; protected ?Zephir\Branch $rootBranch = class Zephir\Branch 
{... }; protected int $uniqueId = 3 }; public ?Zephir\Cache\Manager $cacheManager = class Zephir\Cache\Manager 
{protected ?Zephir\Cache\ClassEntryCache $classEntryCache = NULL; protected ?Zephir\Cache\FunctionCache $functionCache = NULL; protected ?Zephir\Passes\CallGathererPass $gatherer = NULL; protected ?Zephir\Cache\MethodCache $methodCache = NULL; protected ?Zephir\Cache\StaticMethodCache $staticMethodCache = NULL }; public ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{protected string $name = '0__closure'; protected bool $abstract = FALSE; protected ?Zephir\AliasManager $aliasManager = NULL; protected Zephir\Compiler $compiler = class Zephir\Compiler 
{... }; protected array $constants = [...]; protected int $dependencyRank = 0; protected string $docBlock = ''; protected ?string $extendsClass = NULL; protected ?Zephir\Class\Definition\AbstractDefinition $extendsClassDefinition = NULL; protected bool $external = FALSE; protected bool $final = TRUE; protected array $implementedInterfaceDefinitions = [...]; protected array $interfaces = [...]; protected bool $isBundled = FALSE; protected array $methods = [...]; protected array $originalNode = [...]; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $properties = [...]; protected string $shortName = '0__closure'; protected string $type = 'class'; protected string $namespace = 'koalas' }; public ?Zephir\Code\Printer $codePrinter = class Zephir\Code\Printer 
{protected string $code = ''; protected int $currentPrints = 0; protected string $lastLine = ''; protected int $level = 1 }; public ?Zephir\Compiler $compiler = class Zephir\Compiler 
{public array $functionDefinitions = [...]; private array $anonymousFiles = [...]; private array $compiledFiles = [...]; private array $constants = [...]; private array $definitions = [...]; private array $externalDependencies = [...]; private array $extraFiles = [...]; private Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; private array $files = [...]; private array $globals = [...]; private array $internalInitializers = [...]; private ?string $optimizersPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Optimizers'; private ?string $prototypesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/prototypes'; private Zephir\Backend\StringsManager $stringManager = class Zephir\Backend\StringsManager 
{... }; private ?string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates'; private Zephir\Config $config = class Zephir\Config 
{... }; public Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{... }; private Zephir\Parser\Manager $parserManager = class Zephir\Parser\Manager 
{... }; private Zephir\FileSystem\FileSystemInterface $filesystem = class Zephir\FileSystem\HardDisk 
{... }; private Zephir\Compiler\CompilerFileFactory $compilerFileFactory = class Zephir\Compiler\CompilerFileFactory 
{... }; protected $logger = class Monolog\Logger 
{... } }; public ?Zephir\Config $config = class Zephir\Config 
{protected bool $changed = FALSE; private array $container = [...] }; public int $currentBranch = 1; public ?Zephir\Class\Method\Method $currentMethod = class Zephir\Class\Method\Method 
{public bool $optimizable = TRUE; protected ?Zephir\Passes\CallGathererPass $callGathererPass = NULL; protected bool $isAbstract = FALSE; protected bool $isBundled = FALSE; protected bool $isFinal = TRUE; protected bool $isInitializer = FALSE; protected bool $isInternal = FALSE; protected bool $isPublic = TRUE; protected bool $isStatic = FALSE; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected array $mayBeArgTypes = [...]; protected bool $mixed = FALSE; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $returnClassTypes = [...]; protected array $returnTypes = [...]; protected ?array $returnTypesRaw = NULL; protected array $staticVariables = [...]; protected ?Zephir\Passes\StaticTypeInference $typeInference = NULL; protected bool $void = FALSE; protected ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{... }; protected array $visibility = [...]; protected string $name = '__invoke'; protected ?Zephir\Class\Method\Parameters $parameters = class Zephir\Class\Method\Parameters 
{... }; protected ?Zephir\StatementsBlock $statements = class Zephir\StatementsBlock 
{... }; protected ?string $docblock = NULL; protected ?array $expression = [...] }; public int $currentTryCatch = 0; public array $cycleBlocks = []; public ?Zephir\Cache\FunctionCache $functionCache = NULL; public ?Zephir\Code\Printer $headerPrinter = NULL; public ?Zephir\HeadersManager $headersManager = class Zephir\HeadersManager 
{protected array $headers = [...]; protected array $headersFirst = [...]; protected array $headersLast = [...] }; public int $insideCycle = 0; public int $insideSwitch = 0; public int $insideTryCatch = 0; public ?Psr\Log\LoggerInterface $logger = class Monolog\Logger 
{protected $name = 'zephir'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone 
{... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $fiberLogDepth = class WeakMap 
{... }; private $detectCycles = TRUE }; public bool $staticContext = FALSE; public ?Zephir\StringsManager $stringsManager = class Zephir\Backend\StringsManager 
{protected array $concatKeys = [...] }; public ?Zephir\SymbolTable $symbolTable = class Zephir\SymbolTable 
{protected array $branchTempVariables = [...]; protected array $branchVariables = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected bool $mustGrownStack = FALSE; protected int $tempVarCount = 0; protected Zephir\CompilationContext $compilationContext = ... }; public ?Zephir\Passes\StaticTypeInference $typeInference = NULL }) phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Statements/ReturnStatement.php:96
    0.0472   10694200  12. Zephir\MethodCall->compile($expr = class Zephir\Expression 
{protected bool $evalMode = FALSE; protected bool $expecting = TRUE; protected ?Zephir\Variable\Variable $expectingVariable = class Zephir\Variable\Variable 
{protected Zephir\Class\Definition\Definition|ReflectionClass|null $associatedClass = NULL; protected array $classTypes = [...]; protected mixed $defaultInitValue = NULL; protected bool $doublePointer = FALSE; protected array $dynamicTypes = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected bool $idle = FALSE; protected bool $initBranch = FALSE; protected array $initBranches = [...]; protected bool $initialized = TRUE; protected bool $isExternal = FALSE; protected bool $localOnly = FALSE; protected string $lowName = ''; protected bool $memoryTracked = TRUE; protected bool $mustInitNull = FALSE; protected ?array $node = NULL; protected int $numberMutates = 0; protected int $numberSkips = 0; protected int $numberUses = 1; protected mixed $possibleValue = NULL; protected mixed $possibleValueBranch = NULL; protected bool $readOnly = FALSE; protected bool $reusable = TRUE; protected bool $temporal = FALSE; protected bool $used = TRUE; protected ?array $usedNode = NULL; protected int $variantInits = 0; protected string $type = 'variable'; protected string $name = 'return_value'; protected ?Zephir\Branch $branch = class Zephir\Branch 
{... } }; protected bool $noisy = TRUE; protected bool $readOnly = TRUE; protected array $expression = ['type' => 'mcall', 'variable' => [...], 'name' => 'operate', 'call-type' => 1, 'parameters' => [...], 'file' => '/Users/svenschrodt/projects/Koalas_Zep/koalas/koalas/Type/Op/Filter.zep', 'line' => 130, 'char' => 64] }, $compilationContext = class Zephir\CompilationContext 
{public ?Zephir\AliasManager $aliasManager = class Zephir\AliasManager 
{protected array $aliases = [...] }; public ?Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{protected Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; protected Zephir\Config $config = class Zephir\Config 
{... }; protected string $kernelsPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/kernel'; protected string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates' }; public ?Zephir\BranchManager $branchManager = class Zephir\BranchManager 
{protected ?Zephir\Branch $currentBranch = class Zephir\Branch 
{... }; protected int $level = 2; protected ?Zephir\Branch $rootBranch = class Zephir\Branch 
{... }; protected int $uniqueId = 3 }; public ?Zephir\Cache\Manager $cacheManager = class Zephir\Cache\Manager 
{protected ?Zephir\Cache\ClassEntryCache $classEntryCache = NULL; protected ?Zephir\Cache\FunctionCache $functionCache = NULL; protected ?Zephir\Passes\CallGathererPass $gatherer = NULL; protected ?Zephir\Cache\MethodCache $methodCache = NULL; protected ?Zephir\Cache\StaticMethodCache $staticMethodCache = NULL }; public ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{protected string $name = '0__closure'; protected bool $abstract = FALSE; protected ?Zephir\AliasManager $aliasManager = NULL; protected Zephir\Compiler $compiler = class Zephir\Compiler 
{... }; protected array $constants = [...]; protected int $dependencyRank = 0; protected string $docBlock = ''; protected ?string $extendsClass = NULL; protected ?Zephir\Class\Definition\AbstractDefinition $extendsClassDefinition = NULL; protected bool $external = FALSE; protected bool $final = TRUE; protected array $implementedInterfaceDefinitions = [...]; protected array $interfaces = [...]; protected bool $isBundled = FALSE; protected array $methods = [...]; protected array $originalNode = [...]; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $properties = [...]; protected string $shortName = '0__closure'; protected string $type = 'class'; protected string $namespace = 'koalas' }; public ?Zephir\Code\Printer $codePrinter = class Zephir\Code\Printer 
{protected string $code = ''; protected int $currentPrints = 0; protected string $lastLine = ''; protected int $level = 1 }; public ?Zephir\Compiler $compiler = class Zephir\Compiler 
{public array $functionDefinitions = [...]; private array $anonymousFiles = [...]; private array $compiledFiles = [...]; private array $constants = [...]; private array $definitions = [...]; private array $externalDependencies = [...]; private array $extraFiles = [...]; private Zephir\Backend\FcallManagerInterface $fcallManager = class Zephir\Backend\FcallManager 
{... }; private array $files = [...]; private array $globals = [...]; private array $internalInitializers = [...]; private ?string $optimizersPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/src/Optimizers'; private ?string $prototypesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/prototypes'; private Zephir\Backend\StringsManager $stringManager = class Zephir\Backend\StringsManager 
{... }; private ?string $templatesPath = 'phar:///Users/svenschrodt/projects/3rdParty/zephir.phar/templates'; private Zephir\Config $config = class Zephir\Config 
{... }; public Zephir\Backend\Backend $backend = class Zephir\Backend\Backend 
{... }; private Zephir\Parser\Manager $parserManager = class Zephir\Parser\Manager 
{... }; private Zephir\FileSystem\FileSystemInterface $filesystem = class Zephir\FileSystem\HardDisk 
{... }; private Zephir\Compiler\CompilerFileFactory $compilerFileFactory = class Zephir\Compiler\CompilerFileFactory 
{... }; protected $logger = class Monolog\Logger 
{... } }; public ?Zephir\Config $config = class Zephir\Config 
{protected bool $changed = FALSE; private array $container = [...] }; public int $currentBranch = 1; public ?Zephir\Class\Method\Method $currentMethod = class Zephir\Class\Method\Method 
{public bool $optimizable = TRUE; protected ?Zephir\Passes\CallGathererPass $callGathererPass = NULL; protected bool $isAbstract = FALSE; protected bool $isBundled = FALSE; protected bool $isFinal = TRUE; protected bool $isInitializer = FALSE; protected bool $isInternal = FALSE; protected bool $isPublic = TRUE; protected bool $isStatic = FALSE; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected array $mayBeArgTypes = [...]; protected bool $mixed = FALSE; protected ?Zephir\Documentation\Docblock $parsedDocblock = NULL; protected array $returnClassTypes = [...]; protected array $returnTypes = [...]; protected ?array $returnTypesRaw = NULL; protected array $staticVariables = [...]; protected ?Zephir\Passes\StaticTypeInference $typeInference = NULL; protected bool $void = FALSE; protected ?Zephir\Class\Definition\Definition $classDefinition = class Zephir\Class\Definition\Definition 
{... }; protected array $visibility = [...]; protected string $name = '__invoke'; protected ?Zephir\Class\Method\Parameters $parameters = class Zephir\Class\Method\Parameters 
{... }; protected ?Zephir\StatementsBlock $statements = class Zephir\StatementsBlock 
{... }; protected ?string $docblock = NULL; protected ?array $expression = [...] }; public int $currentTryCatch = 0; public array $cycleBlocks = []; public ?Zephir\Cache\FunctionCache $functionCache = NULL; public ?Zephir\Code\Printer $headerPrinter = NULL; public ?Zephir\HeadersManager $headersManager = class Zephir\HeadersManager 
{protected array $headers = [...]; protected array $headersFirst = [...]; protected array $headersLast = [...] }; public int $insideCycle = 0; public int $insideSwitch = 0; public int $insideTryCatch = 0; public ?Psr\Log\LoggerInterface $logger = class Monolog\Logger 
{protected $name = 'zephir'; protected $handlers = [...]; protected $processors = [...]; protected $microsecondTimestamps = TRUE; protected $timezone = class DateTimeZone 
{... }; protected $exceptionHandler = NULL; private $logDepth = 0; private $fiberLogDepth = class WeakMap 
{... }; private $detectCycles = TRUE }; public bool $staticContext = FALSE; public ?Zephir\StringsManager $stringsManager = class Zephir\Backend\StringsManager 
{protected array $concatKeys = [...] }; public ?Zephir\SymbolTable $symbolTable = class Zephir\SymbolTable 
{protected array $branchTempVariables = [...]; protected array $branchVariables = [...]; protected Zephir\Variable\Globals $globalsManager = class Zephir\Variable\Globals 
{... }; protected ?Zephir\Passes\LocalContextPass $localContext = NULL; protected bool $mustGrownStack = FALSE; protected int $tempVarCount = 0; protected Zephir\CompilationContext $compilationContext = ... }; public ?Zephir\Passes\StaticTypeInference $typeInference = NULL })